calculation/calculation_rule.py, calculation/schema.py
TICKET - https://openimis.atlassian.net/browse/OFS-225 
In that PR I want to merge graphQl query to retrieve related class. It might be necessary on frontend to display/show relevant calculation parameters that are related to the certain class/model on chosen page.
https://openimis.atlassian.net/wiki/spaces/OP/pages/2250473529/FS+calculation+rule+1+contribution+valuation
Moreover I refactor two methods for that rule - "check_calculation" and "get_linked_class". I marked that ones on that wiki page as a comment section. Let me know what do you think about it!
=> OFS-225: retrieve classes to frontend and refactor of checkcalculation and get_classes

calculation/calculation_rule.py
ticket https://openimis.atlassian.net/browse/OFS-244
I want to merge changes due to OFS-243 https://openimis.atlassian.net/browse/OFS-243. Please also merge this PR
=> OFS-244: changes due to OFS-243 - json key

README.md
Ticket - https://openimis.atlassian.net/browse/OFS-254 -2 Issue - write documentation for Calculation module.
In that PR I want to add into readme.md description of implemented Calculation module
=> OFS-254: description of the module in README.md file

calculation/schema.py
TICKET: https://openimis.atlassian.net/browse/OFS-274
Includes fixes related to the displaying duplicated params on frontend like in screen:
=> OFS-274: fix duplicating params from calculation rules

calculation/config.py, calculation/schema.py
TICKET: https://openimis.atlassian.net/browse/OFS-279
- solved point a) and b)
=> OFS-279: added 'relevance' and 'condition'

calculation/calculation_rule.py, calculation/config.py, calculation/schema.py, calculation/services.py
TICKET: https://openimis.atlassian.net/browse/OPL-26
changes: 
- added new properties/methods in calculation. 
- added changes in graphQl.
This PR should be merged after this PR: https://github.com/openimis/openimis-be-core_py/pull/85
=> OPL-26: changes in calculation module due to new properties from abstract class

calculation/migrations/0003_add_calculation_roles_for_admin.py
TICKET: https://openimis.atlassian.net/browse/OP-461
=> OP-461: added calculation role for admin

calculation/services.py
TICKET: https://openimis.atlassian.net/browse/OPL-52
hotfix to allow batch run calcrules work.
=> OPL-52: quick 'fix run calculation rules' service

calculation/schema.py
part of TICKET: https://openimis.atlassian.net/browse/OPL-50
Adding uuid filter to fetch particular calculation rule - used in frontend PaymentPlan searcher.
=> OPL-50: added uuid filter in 'resolve_calculation_rules'

calculation/schema.py
TICKET: https://openimis.atlassian.net/browse/OPL-23
=> OPL-23: change in getLinkedClasses for ContributionPlan/PaymentPlan

calculation/calculation_rule.py, calculation/schema.py
part of TICKET: https://openimis.atlassian.net/browse/OPL-84
fixing on backend side those points:
- PaymentPlan need to show only related calcrules
- ContribtuionPlan  need to show only related calcrules
=> OPL-84: added filter for select calcrule types

calculation/calculation_rule.py
TICKET: https://openimis.atlassian.net/browse/OP-478
fixed kwargs in calculate method.
=> OP-478: fixed 'kwargs' in 'calculate' method

calculation/schema.py
TICKET: https://openimis.atlassian.net/browse/OP-762
revert changes - this will be improved during working on that ticket: https://openimis.atlassian.net/browse/OP-760
=> OP-762: revert change for 'relevance' and schema

calculation/services.py
add get_calculation_object function
=> get_calculation_object

calculation/migrations/0003_add_calculation_roles_for_admin.py
Update migrations to support PostgreSQL
=> PostgreSQL support

calculation/migrations/0001_initial.py, calculation/migrations/0003_add_calculation_roles_for_admin.py, calculation/schema.py, calculation/services.py
MERGING RELEASE branches
Release release/22.10
=> MERGING RELEASE branches

calculation/schema.py
Ticket: https://openimis.atlassian.net/browse/OTC-1010
Changes:
- Added missing field in the GQL type.
=> OTC-1010: CalculationParamsGQLType fix.

calculation/calculation_rule.py
Ticket: https://openimis.atlassian.net/browse/OTC-962
Changes:
- Additional condition added in one of the if checks.
=> OTC-962: Conditional check fix.

calculation/calculation_rule.py, calculation/schema.py
[https://openimis.atlassian.net/browse/CM-188](https://openimis.atlassian.net/browse/CM-188)
=> CM-188 Adjusted backend for social protection

calculation/apps.py
https://openimis.atlassian.net/browse/OP-1518
This PR changes the way how config is loaded.
=> OP-1518: load config

calculation/services.py
MERGING release/24.04 into develop
=> MERGING release/24.04 into develop

calculation/calculation_rule.py, calculation/config.py, calculation/migrations/0004_auto_20230126_0903.py, calculation/services.py
MERGING release/24.04 into main
=> MERGING release/24.04 into main
